services:
  - type: web
    name: kanban-task-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: DATABASE_URL
        sync: false
